package com.mycompany.oodj.assignment.dotgroup;

public enum IssueTypeHall {
	AVAILABLE_HALLS_NOT_SHOWING,
	HALL_SELECTION_PROCESS,
	
	INCORRECT_PAYMENT,
	PAYMENT_NOT_SHOWING,
	
	INCORRECT_RECEIPT,
	RECEIPT_NOT_SHOWING,
	
	BOOKING_INFORMATION_NOT_SHOWING,
//	BOOKING_INFORMATION_NOT_SHOWING_AFTER_FILTER,
	CANCELLED_BOOKING_NOT_SHOWING,
}
