package com.mycompany.oodj.assignment.dotgroup;

import java.util.ArrayList;

import java.time.Duration;
import java.time.Period;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;

public class ManagerSalesDashboard extends javax.swing.JFrame {

    FileOperation file = FileOperation.getInstance();
    
    ManagerSalesDashboard sales = new ManagerSalesDashboard();
        
    public ManagerSalesDashboard() {
        initComponents();
        
        
//        ArrayList<Hall> halls = file.read(FileType.HALLS);
//        for (Hall hall : halls) {
//            combo_SalesFilter.addItem(hall.getName());
//            
//            label_TotalSalesFigure.setText("GGGG");
//            System.out.println(combo_SalesFilter);
//        }
        
//        fil
//        
//        cboList = fop.ReadFromFile("./APU/OODJ/JFrame_Login/UserData.txt");
//        
//        for (User e : cboList) {
//            cboUsers.addItem(e.getUserId());
//        }
//        
//        cboUsers.setSelectedIndex(1);
    }

    public void closePanel() {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panel_Body = new javax.swing.JPanel();
        label_TotalSales = new javax.swing.JLabel();
        panel_AsideTotalSalesFigure = new javax.swing.JPanel();
        label_RMSales = new javax.swing.JLabel();
        label_TotalSalesFigure = new javax.swing.JLabel();
        label_YTDSales = new javax.swing.JLabel();
        panel_AsideBookingsSalesFigure = new javax.swing.JPanel();
        label_Bookings = new javax.swing.JLabel();
        label_YTDBookingsRM = new javax.swing.JLabel();
        label_YTDBookingsSalesFigures = new javax.swing.JLabel();
        label_YTDBookings = new javax.swing.JLabel();
        label_TotalBookingsRM = new javax.swing.JLabel();
        label_TotalBookingsSalesFigures = new javax.swing.JLabel();
        label_TotalBookings = new javax.swing.JLabel();
        panel_ContentSalesFilter = new javax.swing.JPanel();
        combo_SalesFilter = new javax.swing.JComboBox<>();
        label_SalesMade = new javax.swing.JLabel();
        label_YTDBookingsSalesFigures1 = new javax.swing.JLabel();
        label_SalesMadeFilter = new javax.swing.JLabel();
        button_FilterUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_TotalSales.setFont(new java.awt.Font("MesloLGM Nerd Font Mono", 1, 24)); // NOI18N
        label_TotalSales.setText("Total Sales");

        panel_AsideTotalSalesFigure.setBackground(new java.awt.Color(0, 153, 204));
        panel_AsideTotalSalesFigure.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_AsideTotalSalesFigure.setForeground(new java.awt.Color(153, 153, 153));

        label_RMSales.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label_RMSales.setText("RM");

        label_TotalSalesFigure.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        label_TotalSalesFigure.setText("1.43M");

        label_YTDSales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_YTDSales.setText("YTD");

        javax.swing.GroupLayout panel_AsideTotalSalesFigureLayout = new javax.swing.GroupLayout(panel_AsideTotalSalesFigure);
        panel_AsideTotalSalesFigure.setLayout(panel_AsideTotalSalesFigureLayout);
        panel_AsideTotalSalesFigureLayout.setHorizontalGroup(
            panel_AsideTotalSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AsideTotalSalesFigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_AsideTotalSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_RMSales)
                    .addComponent(label_TotalSalesFigure)
                    .addGroup(panel_AsideTotalSalesFigureLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(label_YTDSales)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panel_AsideTotalSalesFigureLayout.setVerticalGroup(
            panel_AsideTotalSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AsideTotalSalesFigureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_RMSales, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_TotalSalesFigure, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_YTDSales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_AsideBookingsSalesFigure.setBackground(new java.awt.Color(0, 153, 204));
        panel_AsideBookingsSalesFigure.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_Bookings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_Bookings.setText("Bookings");

        label_YTDBookingsRM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_YTDBookingsRM.setText("RM");

        label_YTDBookingsSalesFigures.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        label_YTDBookingsSalesFigures.setText("1.43M");

        label_YTDBookings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_YTDBookings.setText("YTD");

        label_TotalBookingsRM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_TotalBookingsRM.setText("RM");

        label_TotalBookingsSalesFigures.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        label_TotalBookingsSalesFigures.setText("1.43M");

        label_TotalBookings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_TotalBookings.setText("Total bookings");

        javax.swing.GroupLayout panel_AsideBookingsSalesFigureLayout = new javax.swing.GroupLayout(panel_AsideBookingsSalesFigure);
        panel_AsideBookingsSalesFigure.setLayout(panel_AsideBookingsSalesFigureLayout);
        panel_AsideBookingsSalesFigureLayout.setHorizontalGroup(
            panel_AsideBookingsSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AsideBookingsSalesFigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_AsideBookingsSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_TotalBookings)
                    .addComponent(label_Bookings)
                    .addComponent(label_YTDBookingsRM)
                    .addComponent(label_YTDBookingsSalesFigures)
                    .addComponent(label_YTDBookings)
                    .addComponent(label_TotalBookingsRM)
                    .addComponent(label_TotalBookingsSalesFigures))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panel_AsideBookingsSalesFigureLayout.setVerticalGroup(
            panel_AsideBookingsSalesFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AsideBookingsSalesFigureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Bookings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_YTDBookingsRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_YTDBookingsSalesFigures, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_YTDBookings)
                .addGap(24, 24, 24)
                .addComponent(label_TotalBookingsRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_TotalBookingsSalesFigures, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_TotalBookings)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        panel_ContentSalesFilter.setBackground(new java.awt.Color(0, 153, 204));
        panel_ContentSalesFilter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combo_SalesFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combo_SalesFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hourly", "Weekly", "Monthly", "Yearly" }));

        label_SalesMade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_SalesMade.setText("Monthly Sales ");

        label_YTDBookingsSalesFigures1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_YTDBookingsSalesFigures1.setText("RM");

        label_SalesMadeFilter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_SalesMadeFilter.setText("Filter");

        button_FilterUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_FilterUpdate.setText("Update");
        button_FilterUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FilterUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ContentSalesFilterLayout = new javax.swing.GroupLayout(panel_ContentSalesFilter);
        panel_ContentSalesFilter.setLayout(panel_ContentSalesFilterLayout);
        panel_ContentSalesFilterLayout.setHorizontalGroup(
            panel_ContentSalesFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContentSalesFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ContentSalesFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_SalesMade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_YTDBookingsSalesFigures1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_ContentSalesFilterLayout.createSequentialGroup()
                        .addGroup(panel_ContentSalesFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_SalesMadeFilter)
                            .addGroup(panel_ContentSalesFilterLayout.createSequentialGroup()
                                .addComponent(combo_SalesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_FilterUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_ContentSalesFilterLayout.setVerticalGroup(
            panel_ContentSalesFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContentSalesFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_SalesMadeFilter)
                .addGap(39, 39, 39)
                .addGroup(panel_ContentSalesFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_FilterUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_SalesFilter))
                .addGap(32, 32, 32)
                .addComponent(label_SalesMade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_YTDBookingsSalesFigures1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_BodyLayout = new javax.swing.GroupLayout(panel_Body);
        panel_Body.setLayout(panel_BodyLayout);
        panel_BodyLayout.setHorizontalGroup(
            panel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BodyLayout.createSequentialGroup()
                .addComponent(panel_AsideTotalSalesFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_AsideBookingsSalesFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ContentSalesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 249, Short.MAX_VALUE))
            .addGroup(panel_BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_TotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_BodyLayout.setVerticalGroup(
            panel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BodyLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TotalSales)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_ContentSalesFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_AsideBookingsSalesFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_AsideTotalSalesFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_FilterUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FilterUpdateActionPerformed
//        ArrayList<Sales> sales = new ArrayList<Sales>;
        
        System.out.println(combo_SalesFilter.getSelectedItem().toString());
        
        String currentFilter = combo_SalesFilter.getSelectedItem().toString();
        
//        System.out.println(file.read2(FileType.SALES));
    
//        ArrayList<Sales> sales = sales.get(combo_SalesFilter.getSelectedIndex());
        
//        for (Sales sale : sales) {
//            System.out.println(sale);
//        }
        
//        int currentFilter = combo_SalesFilter.get(combo_SalesFilter.getSelectedIndex());
    }//GEN-LAST:event_button_FilterUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManagerSalesDatabase panel = new ManagerSalesDatabase();
        panel.setVisible(true);
        closePanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSalesDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSalesDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSalesDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSalesDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerSalesDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_FilterUpdate;
    private javax.swing.JComboBox<String> combo_SalesFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label_Bookings;
    private javax.swing.JLabel label_RMSales;
    private javax.swing.JLabel label_SalesMade;
    private javax.swing.JLabel label_SalesMadeFilter;
    private javax.swing.JLabel label_TotalBookings;
    private javax.swing.JLabel label_TotalBookingsRM;
    private javax.swing.JLabel label_TotalBookingsSalesFigures;
    private javax.swing.JLabel label_TotalSales;
    private javax.swing.JLabel label_TotalSalesFigure;
    private javax.swing.JLabel label_YTDBookings;
    private javax.swing.JLabel label_YTDBookingsRM;
    private javax.swing.JLabel label_YTDBookingsSalesFigures;
    private javax.swing.JLabel label_YTDBookingsSalesFigures1;
    private javax.swing.JLabel label_YTDSales;
    private javax.swing.JPanel panel_AsideBookingsSalesFigure;
    private javax.swing.JPanel panel_AsideTotalSalesFigure;
    private javax.swing.JPanel panel_Body;
    private javax.swing.JPanel panel_ContentSalesFilter;
    // End of variables declaration//GEN-END:variables
}
