package com.mycompany.oodj.assignment.dotgroup;

import java.swing.table.DefaultTableMoodle;

public class SalesDatabase extends javax.swing.JFrame {

    public SalesDatabase() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_PanelMain = new javax.swing.JPanel();
        label_SalesDashboardTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_SalesDashboard = new javax.swing.JTable();
        aside_PanelFilter = new javax.swing.JPanel();
        label_HallType = new javax.swing.JLabel();
        radio_HallAuditorium = new javax.swing.JRadioButton();
        radio_HallBanquet = new javax.swing.JRadioButton();
        radio_HallMeetingRoom = new javax.swing.JRadioButton();
        button_Filter = new javax.swing.JButton();
        label_Sales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body_PanelMain.setBackground(new java.awt.Color(0, 0, 51));

        label_SalesDashboardTitle.setBackground(new java.awt.Color(204, 255, 255));
        label_SalesDashboardTitle.setFont(new java.awt.Font("MesloLGM Nerd Font", 1, 24)); // NOI18N
        label_SalesDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        label_SalesDashboardTitle.setText("Sales Dashboard");

        table_SalesDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Customer ID", "Customer Name", "Start DateTime", "End DateTime", "Duration", "Hall Type", "Reason", "Sales (RM)"
            }
        ));
        jScrollPane1.setViewportView(table_SalesDashboard);
        if (table_SalesDashboard.getColumnModel().getColumnCount() > 0) {
            table_SalesDashboard.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        aside_PanelFilter.setBackground(new java.awt.Color(0, 153, 204));

        label_HallType.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_HallType.setForeground(new java.awt.Color(255, 255, 255));
        label_HallType.setText("Hall Type");

        radio_HallAuditorium.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radio_HallAuditorium.setForeground(new java.awt.Color(255, 255, 255));
        radio_HallAuditorium.setText("Auditorium");
        radio_HallAuditorium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_HallAuditoriumActionPerformed(evt);
            }
        });

        radio_HallBanquet.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radio_HallBanquet.setForeground(new java.awt.Color(255, 255, 255));
        radio_HallBanquet.setText("Banquet Hall");

        radio_HallMeetingRoom.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radio_HallMeetingRoom.setForeground(new java.awt.Color(255, 255, 255));
        radio_HallMeetingRoom.setText("Meeting Room");

        button_Filter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        button_Filter.setText("Filter");
        button_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FilterActionPerformed(evt);
            }
        });

        label_Sales.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_Sales.setForeground(new java.awt.Color(255, 255, 255));
        label_Sales.setText("Sales ");

        javax.swing.GroupLayout aside_PanelFilterLayout = new javax.swing.GroupLayout(aside_PanelFilter);
        aside_PanelFilter.setLayout(aside_PanelFilterLayout);
        aside_PanelFilterLayout.setHorizontalGroup(
            aside_PanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aside_PanelFilterLayout.createSequentialGroup()
                .addGroup(aside_PanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aside_PanelFilterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(aside_PanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_HallType)
                            .addComponent(radio_HallAuditorium)
                            .addComponent(radio_HallBanquet)
                            .addComponent(radio_HallMeetingRoom)
                            .addComponent(label_Sales)))
                    .addGroup(aside_PanelFilterLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(button_Filter)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        aside_PanelFilterLayout.setVerticalGroup(
            aside_PanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aside_PanelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_HallType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_HallAuditorium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_HallBanquet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_HallMeetingRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Sales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Filter)
                .addContainerGap())
        );

        javax.swing.GroupLayout body_PanelMainLayout = new javax.swing.GroupLayout(body_PanelMain);
        body_PanelMain.setLayout(body_PanelMainLayout);
        body_PanelMainLayout.setHorizontalGroup(
            body_PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body_PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_PanelMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aside_PanelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(body_PanelMainLayout.createSequentialGroup()
                        .addComponent(label_SalesDashboardTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        body_PanelMainLayout.setVerticalGroup(
            body_PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_PanelMainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_SalesDashboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aside_PanelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body_PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_HallAuditoriumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_HallAuditoriumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_HallAuditoriumActionPerformed

    private void button_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_FilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SalesDatabase().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aside_PanelFilter;
    private javax.swing.JPanel body_PanelMain;
    private javax.swing.JButton button_Filter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_HallType;
    private javax.swing.JLabel label_Sales;
    private javax.swing.JLabel label_SalesDashboardTitle;
    private javax.swing.JRadioButton radio_HallAuditorium;
    private javax.swing.JRadioButton radio_HallBanquet;
    private javax.swing.JRadioButton radio_HallMeetingRoom;
    private javax.swing.JTable table_SalesDashboard;
    // End of variables declaration//GEN-END:variables
}
