/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj.assignment.dotgroup.forms;

/**
 *
 * @author Frogm
 
 */

import javax.swing.ListModel;

public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        
        text_IssueType.setText("GGGG");
        text_Resolution.setText("Unresolved");
        text_VersionFixed.setText("1.2");
        text_VersionAffected.setText("1.0");
        text_Environment.setText("Windows");
        text_ConfirmationStatus.setText("Unconfirmed");
        text_Category.setText("Category");
        textarea_Description.setText("TEXT AREA");
        
        System.out.println(list_IssueMenu.getModel().toString());
        
        System.out.println(list_IssueMenu.getModel().getClass().getName());
        
        // Clear the current table data
//        model.setElementAt(0);
//        System.out.println(model.size());
//        GTry();
        // Add rows to the table for each employee
//        for (String emp : employees) {
//            model.addRow(new Object[]{emp.getEmpId(), emp.getEmpName(), emp.getSalary(), emp.getEmpId()});
//        }
        
//        list_IssueMenu.setModel();
    }

    public void GTry() {
        ListModel model = (ListModel)list_IssueMenu.getModel();
        
        System.out.println(list_IssueMenu.getModel().getClass().getName());
        
        // Clear the current table data
        
//        for (int i = 0; i <= 5; i++) {
//            System.out.println(model.getElementAt(i));
//            model.addListDataListener(l);
//        
//        }
//        
//        System.out.println(model.size());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label_IssueTitle = new javax.swing.JLabel();
        label_IssueTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_IssueMenu = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        label_IssueType = new javax.swing.JLabel();
        label_Resolution = new javax.swing.JLabel();
        label_VersionFixed = new javax.swing.JLabel();
        label_VersionAffected = new javax.swing.JLabel();
        label_Environment = new javax.swing.JLabel();
        label_ConfirmationStatus = new javax.swing.JLabel();
        label_Category = new javax.swing.JLabel();
        label_Description = new javax.swing.JLabel();
        text_ConfirmationStatus = new javax.swing.JTextField();
        text_Category = new javax.swing.JTextField();
        text_Environment = new javax.swing.JTextField();
        text_VersionAffected = new javax.swing.JTextField();
        text_VersionFixed = new javax.swing.JTextField();
        text_Resolution = new javax.swing.JTextField();
        text_IssueType = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        textarea_Description = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        label_Reporter = new javax.swing.JLabel();
        label_Reporter1 = new javax.swing.JLabel();
        label_Reporter2 = new javax.swing.JLabel();
        label_Reporter3 = new javax.swing.JLabel();
        label_Reporter4 = new javax.swing.JLabel();
        label_Reporter5 = new javax.swing.JLabel();
        label_Reporter6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_IssueTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_IssueTitle.setText("SAMPLE-IssueTitle");

        label_IssueTitle1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_IssueTitle1.setText("SAMPLE-IssueID");

        list_IssueMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_IssueMenu);

        label_IssueType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_IssueType.setText("IssueType");

        label_Resolution.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Resolution.setText("Resolution");

        label_VersionFixed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_VersionFixed.setText("Version Fixed");

        label_VersionAffected.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_VersionAffected.setText("Version Affected");

        label_Environment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Environment.setText("Environment");

        label_ConfirmationStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_ConfirmationStatus.setText("Confirmation Status");

        label_Category.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Category.setText("Category");

        label_Description.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Description.setText("Description");

        text_ConfirmationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ConfirmationStatusActionPerformed(evt);
            }
        });

        text_Environment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_EnvironmentActionPerformed(evt);
            }
        });

        text_VersionAffected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_VersionAffectedActionPerformed(evt);
            }
        });

        text_VersionFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_VersionFixedActionPerformed(evt);
            }
        });

        text_Resolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ResolutionActionPerformed(evt);
            }
        });

        text_IssueType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_IssueTypeActionPerformed(evt);
            }
        });

        textarea_Description.setColumns(20);
        textarea_Description.setRows(5);
        jScrollPane3.setViewportView(textarea_Description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_ConfirmationStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_ConfirmationStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_Category)
                        .addGap(74, 74, 74)
                        .addComponent(text_Category))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_Environment)
                        .addGap(52, 52, 52)
                        .addComponent(text_Environment))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_VersionAffected)
                        .addGap(30, 30, 30)
                        .addComponent(text_VersionAffected))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_VersionFixed)
                        .addGap(49, 49, 49)
                        .addComponent(text_VersionFixed))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_IssueType)
                        .addGap(68, 68, 68)
                        .addComponent(text_IssueType))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_Resolution)
                        .addGap(64, 64, 64)
                        .addComponent(text_Resolution))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_Description)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_IssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_IssueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Resolution, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Resolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_VersionFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_VersionFixed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_VersionAffected, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_VersionAffected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Environment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Environment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ConfirmationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_ConfirmationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        label_Reporter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter.setText("Reporter");

        label_Reporter1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter1.setText("Assignee:");

        label_Reporter2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter2.setText("Unassigned");

        label_Reporter3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter3.setText("Reporter:");

        label_Reporter4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter4.setText("Unassigned");

        label_Reporter5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter5.setText("Date");

        label_Reporter6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Reporter6.setText("Created: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Reporter)
                    .addComponent(label_Reporter1)
                    .addComponent(label_Reporter2)
                    .addComponent(label_Reporter3)
                    .addComponent(label_Reporter4)
                    .addComponent(label_Reporter5)
                    .addComponent(label_Reporter6))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Reporter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Reporter1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Reporter2)
                .addGap(18, 18, 18)
                .addComponent(label_Reporter3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Reporter4)
                .addGap(18, 18, 18)
                .addComponent(label_Reporter5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Reporter6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_IssueTitle)
                            .addComponent(label_IssueTitle1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_IssueTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_IssueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manager");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_ConfirmationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ConfirmationStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ConfirmationStatusActionPerformed

    private void text_EnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_EnvironmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_EnvironmentActionPerformed

    private void text_VersionAffectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_VersionAffectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_VersionAffectedActionPerformed

    private void text_VersionFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_VersionFixedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_VersionFixedActionPerformed

    private void text_ResolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ResolutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ResolutionActionPerformed

    private void text_IssueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_IssueTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_IssueTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_Category;
    private javax.swing.JLabel label_ConfirmationStatus;
    private javax.swing.JLabel label_Description;
    private javax.swing.JLabel label_Environment;
    private javax.swing.JLabel label_IssueTitle;
    private javax.swing.JLabel label_IssueTitle1;
    private javax.swing.JLabel label_IssueType;
    private javax.swing.JLabel label_Reporter;
    private javax.swing.JLabel label_Reporter1;
    private javax.swing.JLabel label_Reporter2;
    private javax.swing.JLabel label_Reporter3;
    private javax.swing.JLabel label_Reporter4;
    private javax.swing.JLabel label_Reporter5;
    private javax.swing.JLabel label_Reporter6;
    private javax.swing.JLabel label_Resolution;
    private javax.swing.JLabel label_VersionAffected;
    private javax.swing.JLabel label_VersionFixed;
    private javax.swing.JList<String> list_IssueMenu;
    private javax.swing.JTextField text_Category;
    private javax.swing.JTextField text_ConfirmationStatus;
    private javax.swing.JTextField text_Environment;
    private javax.swing.JTextField text_IssueType;
    private javax.swing.JTextField text_Resolution;
    private javax.swing.JTextField text_VersionAffected;
    private javax.swing.JTextField text_VersionFixed;
    private javax.swing.JTextArea textarea_Description;
    // End of variables declaration//GEN-END:variables
}
